INSERT INTO Mahasiswa (id, nama)
VALUES 
    (1, 'Amoy'),
    (2, 'Gyatt'),
    (3, 'Rizz'),
    (4, 'Sigma'),
    (5, 'Mewing'),
	(6, 'Ohio'),
	(7, 'Takde'),
	(8, 'Biji'),
	(9, 'Kau'),
	(10, 'Nak'),
	(11, 'Mewing'),
	(12, 'Betul'),
	(13, 'Ke'),
	(14, '?'),
	(15, 'Atoto'),
	(16, 'Wutdeheel'),
	(17, 'Tolong'),
	(18, 'Saya'),
	(19, 'Mewing Part 2'),
	(20, 'Apel');